steps:
#  - name: gcr.io/cloud-builders/docker
#    args: ['build', '.', '-t', '${_IMG_TAG}']
#    timeout: 3600s
#
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['push', '${_IMG_TAG}']
#
#  - name: gcr.io/cloud-builders/gcloud
#    entrypoint: 'bash'
#    args: [ '-c', "mkdir /root/.hail; echo \"{\\\"default\\\": \\\"$(gcloud secrets versions access latest --secret='hail-token')\\\"}\" > tokens.json" ]
#
#  - name: australia-southeast1-docker.pkg.dev/vlad-dev/test-ci/hailbatch
#    entrypoint: 'bash'
#    args: ['-x', '-c', "mkdir ~/.hail; cp tokens.json ~/.hail/; cp /hail-deploy-config.json ~/.hail/deploy-config.json; python test/run_ci_with_batch.py ${_IMG_TAG}"]
#
#  - name: australia-southeast1-docker.pkg.dev/vlad-dev/test-ci/hailbatch
#    entrypoint: 'bash'
#    args: ['-x', '-c', "mkdir ~/.hail; cp tokens.json ~/.hail/; cp /hail-deploy-config.json ~/.hail/deploy-config.json; python test/run_ci_with_batch.py ${_IMG_TAG}"]
#
  - name: ubuntu
    entrypoint: 'bash'
    args: ['-x', '-c', "IMG_TAG=${_IMG_TAG}; echo ${IMG_TAG//dev/$TAG_NAME}"]

  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args: ['-x', '-c', "IMG_TAG=${_IMG_TAG}; [ ! -z $TAG_NAME ] && docker tag ${IMG_TAG} ${IMG_TAG//dev/$TAG_NAME} && docker push ${IMG_TAG//dev/$TAG_NAME} || echo 'Skiping pushing the image as the git tag is not defined'"]

substitutions:
    _IMG_TAG: australia-southeast1-docker.pkg.dev/vlad-dev/test-ci/test-ci:dev

timeout: 3600s
