steps:
  - name: gcr.io/cloud-builders/gcloud
    args: ['builds', 'submit', '.', '--tag=australia-southeast1-docker.pkg.dev/vlad-dev/test-ci/test-ci:dev']

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "mkdir /root/.hail; echo \"{\\\"default\\\": \\\"$(gcloud secrets versions access latest --secret='hail-token')\\\"}\" > tokens.json" ]

  - name: australia-southeast1-docker.pkg.dev/vlad-dev/test-ci/hailbatch
    entrypoint: 'bash'
    args: ['-x', '-c', "mkdir ~/.hail; cp tokens.json ~/.hail/; cp /hail-deploy-config.json ~/.hail/deploy-config.json; python test/run_ci_with_batch.py australia-southeast1-docker.pkg.dev/vlad-dev/test-ci/test-ci:dev"]
