steps:
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'australia-southeast1-docker.pkg.dev/vlad-dev/test-ci/test-ci:latest', '.']
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "mkdir /root/.hail; gcloud secrets versions access latest --secret='hail-token' > /root/.hail/tokens.json" ]

  - name: ubuntu
    entrypoint: 'bash'
    args: [ '-c', "echo '{\"location\": \"external\", \"default_namespace\": \"default\", \"service_namespace\": {}, \"domain\": \"hail.populationgenomics.org.au\"}' > /root/.hail/deploy-config.json" ]

  - name: 'australia-southeast1-docker.pkg.dev/vlad-dev/test-ci/hailbatch'
    entrypoint: 'python'
    args: ['test/run_ci_with_batch.py', 'australia-southeast1-docker.pkg.dev/vlad-dev/test-ci/test-ci']


#docker run -v $HOME/.hail:/root/.hail -v $PWD:$PWD -ti australia-southeast1-docker.pkg.dev/vlad-dev/test-ci/hailbatch python $PWD/test/run_ci_with_batch.py australia-southeast1-docker.pkg.dev/vlad-dev/test-ci/test-ci


