{% set data=load_setup_py_data() %}

package:
  name: test_ci
  version: {{ data['version'] }}

source:
  path: ../../

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
    - hail >=0.2.61    
    - pysam
  run:
    - python
    - hail >=0.2.61
    - google-cloud-storage
    - click
test:
  commands:
    - test_ci
    
about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
