name: CI
on: [push, pull_request]

jobs:
  build-test-publish:
    # For tag pushes, we want to assure only the tag event triggers CI,
    # not the accompanying commit:
    if: "! startsWith(github.event.head_commit.message, 'Bump ') || startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@master

      # - name: Build the image
      #   run: |
      #     docker build . -t docker.io/vladsaveliev/test_ci

      # - name: Push the image
      #   run: |
      #     docker push docker.io/vladsaveliev/test_ci

      - name: Set up Hail Batch token
        run: |
          mkdir ${HOME}/.hail
          echo '{"default": "${{ secrets.HAIL_BATCH_CPG_CI_TOKEN }}"}' > ${HOME}/.hail/tokens.json
          echo '{"location": "external", "default_namespace": "default", "service_namespace": {}, "domain": "hail.populationgenomics.org.au"}' > ${HOME}/.hail/deploy-config.json

      - name: Add miniconda to PATH
        run: echo "PATH=${HOME}/miniconda3/bin:${PATH}" >> $GITHUB_ENV

      - name: Setup conda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.9.2-Linux-x86_64.sh \
            --no-verbose -O miniconda.sh
          bash miniconda.sh -b
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels bioconda --add channels conda-forge --add channels cpg

      - name: Create environment for Hail
        run: |
          conda create -n hailenv hail google-cloud-storage
          echo "PATH=${HOME}/miniconda3/envs/hailenv/bin:${PATH}" >> $GITHUB_ENV

      - name: Run tests
        run: |
          python test/run_ci_with_batch.py docker.io/vladsaveliev/test_ci













