name: CI
on: [push, pull_request]

jobs:
  build-test-publish:
    # For tag pushes, we want to assure only the tag event triggers CI,
    # not the accompanying commit:
    if: "! startsWith(github.event.head_commit.message, 'Bump ') || startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@master

      - name: Add miniconda to PATH
        run: echo "PATH=${HOME}/miniconda3/bin:${PATH}" >> $GITHUB_ENV

      - name: Setup conda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.9.2-Linux-x86_64.sh \
            --no-verbose -O miniconda.sh
          bash miniconda.sh -b
          conda config --set always_yes yes --set changeps1 no
          conda install -c conda-forge mamba "python==${{ matrix.python-version }}.*"
          mamba update conda
          conda config --add channels cpg --add channels bioconda --add channels conda-forge
          mamba install pip conda-build conda-verify anaconda-client
          pip install versionpy

      - id: gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: "cpg-ci"
          service_account_key: "${{ secrets.HAIL_BATCH_CPG_CI_TOKEN }}"
          export_default_credentials: true

      - name: Build package
        run: mamba build conda/$(basename $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')

      - name: Install
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: mamba install --use-local $(basename $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')

      - name: Test
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          export PATH="${HOME}/miniconda3/bin:${PATH}"
          cd test
          source test.sh

      - name: Upload to anaconda
        if: "startsWith(github.ref, 'refs/tags/')"
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} \
          upload --force ${HOME}/miniconda3/conda-bld/**/*.tar.bz2
